FROM ubuntu:latest

LABEL name="shivaram"

# Setting environment variables for AWS
ENV AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXXXXXX \
    AWS_SECRET_KEY_ID=XXXXXXXXXXXXXXXXXXXXXXXX \
    AWS_DEFAULT_REGION=us-east-1

# Defining Terraform and Packer versions
ARG T_VERSION='1.6.6' \
    P_VERSION='1.8.0'

# Installing necessary packages
RUN apt update && apt install -y jq net-tools curl wget unzip \
    && apt install -y nginx iputils-ping 

# Downloading and installing Terraform and Packer
RUN wget https://releases.hashicorp.com/terraform/${T_VERSION}/terraform_${T_VERSION}_linux_amd64.zip \
    && wget https://releases.hashicorp.com/packer/${P_VERSION}/packer_${P_VERSION}_linux_amd64.zip \
    && unzip terraform_${T_VERSION}_linux_amd64.zip \
    && unzip packer_${P_VERSION}_linux_amd64.zip \
    && mv terraform /usr/local/bin/ && mv packer /usr/local/bin/ \
    && chmod +x /usr/local/bin/terraform /usr/local/bin/packer \
    && terraform version && packer version 

# Starting NGINX
CMD ["nginx", "-g", "daemon off;"]
